### ISSUE TITLE
[ERROR@mausignald] Connection to /var/run/signald/signald.sock failed: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/mautrix_signal_ynh#13]
### Describe the bug

Right after installing, looking at the logs of mautrix-signal with `journalctl -u mautrix_signal.service`, this error was repeated multiple times.

I found that similar issue: https://github.com/mautrix/signal/issues/45#issuecomment-881766204

**I fixed it on my end** by adding the mautrix_signal user to the signald group:

```
usermod -aG signald mautrix_signal
```

~~Although the bot user still doesn't accept my invitations.~~ It did a bit later.

Edit: also necessary to add +x permission to the avatars directory for the group:

```
chmod g+rwX /var/lib/signald/avatars
```

An alternative may be to change the group owning the sockets and directories to mautrix_signal or some shared group, but that didn't work when I tried it.

### Context

- Hardware: x86_64 bare metal
- YunoHost version: 
- I have access to my server: ssh, webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: not relevant to this issue AFAIK
- Using, or trying to install package version/branch: https://github.com/MayeulC/mautrix_signal_ynh/tree/MayeulC-fix-checksum

### Steps to reproduce

- Install the bridge
- Look at the logs

**Comment by Gredin67** [comment]
what about using one single user for mautrix_signal and signald ? And installing signald from source in /opt/yunohost/signald
See my last commits on the testing branch. Feel free to commit directly to the testing branch.

**Comment by Gredin67** [comment]
@MayeulC I gave you write access to the repo. You could try to implement your changes in groups and users in debian-repo branch where signald is installed from its debian package. 

If this is not sufficient I guess we should switch to building signald from source and setup debian folders, users, rights, dependencies, systemd, etc correctly. I started this in the testing branch.
