### ISSUE TITLE
Install fail on master (user interface) and test (CLI)

### ISSUE THREAD

**Issue by letime64** [YunoHost-Apps/mautrix_signal_ynh#30]
### Describe the bug

I''m not able to install the package for the first time (not installed before) from user interface or CLI.

### Context

- Hardware: Gandi VPS with VPN (openvpn)
- YunoHost version: 4.2.8.3
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: master using the user interface and test using the CLI

### Steps to reproduce

In user interface :
1. Go to Application
2. Go to Install +
3. Look for Mautrix_signal and clic install
4. Installation is not going through and fail -> produce log

In the CLI:
1. Run `sudo yunohost app install https://github.com/YunoHost-Apps/mautrix_signal_ynh/tree/testing --debug`
2. Install go through, VPS is not responsive at one point (error 500 for the whole server) then is back
3. Installation is not going through and fail -> produce log

### Expected behavior

Installation of mautrix_signal go through

### Logs

Logs from user interface : https://paste.yunohost.org/raw/obexovajig
Logs from CLI : https://paste.yunohost.org/raw/wiraqayezu

**Comment by MayeulC** [comment]
```
2021-11-15 14:23:17,585: WARNING - E: Unable to locate package (>
2021-11-15 14:23:17,595: WARNING - E: Unable to locate package 0.15)
2021-11-15 14:23:17,596: WARNING - E: Couldn't find any package by glob '0.15)'
2021-11-15 14:23:17,596: WARNING - E: Couldn't find any package by regex '0.15)'
2021-11-15 14:23:17,596: DEBUG - + ynh_die '--message=Unable to install dependencies'```

I recall seing this earlier, but it now works. Try upgrading yunohost? I'm now at version 4.3.3, you're at version 4.2.8.3.

**Comment by letime64** [comment]
I upgraded all the installation (yunohost and other package including synapse). I tried to install the master again from the user interface and it didn't work.

New logs can be found here : https://paste.yunohost.org/raw/kokucihome

**Comment by letime64** [comment]
The master didn't went through but the test branch worked after a failed test install followed by a reboot. The latest issues seems to have come from my system.

Logs of the successful install : https://paste.yunohost.org/raw/ilakalalik

**Comment by MayeulC** [comment]
Thanks for the report. Besides your temporary, machine-dependent issue (`FATAL -> Failed to fork.`), it is the same issue as #29, and somehow works with testing.
