### ISSUE TITLE
Installation: SyntaxError: invalid syntax  

### ISSUE THREAD

**Issue by karpaz** [YunoHost-Apps/mautrix_signal_ynh#38]
Hello
I've got some problems with signal bridge, because I cannot send messages to group on signal,
```
⚠ Your message was not bridged: IllegalStateException: invalid state for call to sealed_sender_multi_recipient_encrypt to succeed: cannot get registration ID from session with 23f97968-dde0-4de0-80d3-03f6b9f42369.1 (maybe it was recently archived)
```

I tried to uninstall yunohost package with command `sudo yunohost app remove mautrix_signal`
and after that install it with this command `sudo yunohost app install https://github.com/YunoHost-Apps/mautrix_signal_ynh/tree/master --debug`
This doesn't work, so I tried testing branch with no success... my log is here
https://paste.yunohost.org/raw/kosiceyefe

I will be very glad if you find any time to help me. Hope it helps other people too, if is something incorrect on GitHub repository. :)
--- 

### Context

- Hardware: * Raspberry Pi at home *
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain: 
- Using, or trying to install package version/branch: master and also testing

**Comment by Gredin67** [comment]
please try the new version and open a new issue if the problem remains.
