### ISSUE TITLE
Install fail due to missing rust compiler

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/mautrix_signal_ynh#41]
### Describe the bug

Install fail due to missing rust compiler

### Context

- Hardware: *odroid hc1 armhf(v7)*
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: inside lxc container
- Using, or trying to install package version/branch: master
- If upgrading, current package version: *NA*

### Steps to reproduce

- ```sh
    sudo yunohost app install mautrix_signal
    ```

### Expected behavior

*install mautrix_signal plugin*

### Logs

*[LOGs](https://paste.yunohost.org/raw/olopomavup)*

**Comment by Gredin67** [comment]
please try the new version and open a new issue if the problem remains.

**Comment by rosbeef** [comment]
new version -> not working 
i update pip -> not working
i install rustc with package (sudo apt install rustc) -> working

**Comment by Gredin67** [comment]
if you are on yunohost 11 do install the bullseye branch
`sudo yunohost app install https://github.com/YunoHost-Apps/mautrix_signal_ynh/tree/bullseye`
If you are still on yunohost 4,  install the testing branch
`sudo yunohost app install https://github.com/YunoHost-Apps/mautrix_signal_ynh/tree/testing`

**Comment by rosbeef** [comment]
it's not working on yunohost 4
https://paste.yunohost.org/vuxezudawe
seems to be a python script problem

**Comment by rosbeef** [comment]
maybe it's linked with las release.
