### ISSUE TITLE
testing branch version

### ISSUE THREAD

**Issue by zunami** [YunoHost-Apps/mautrix_signal_ynh#48]
the version [0.3.0](https://github.com/mautrix/signal/releases/tag/v0.3.0) ist out now
is it possible to start this in the test area?

**Comment by MayeulC** [comment]
By test area, you mean the `testing` branch?

Unfortunately, as #47 mentions, mautrix-python dropped support for debian buster, so it cannot be directly installed; you'd have to upgrade to debian bullseye, or run the bridge in a container.

**Comment by Gredin67** [comment]
@zunami you can try the testing branch. If it doesn't work for you please reopen the issue
