### ISSUE TITLE
Missing ynh_use_logrotate --nonappend arg in the upgrade script

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/mautrix_signal_ynh#49]
Exactly the same as https://github.com/YunoHost-Apps/mautrix_whatsapp_ynh/issues/59

The upgrade script is missing --nonappend argument to ynh_use_logrotate.

What is happening here is that the /etc/logrotate.d/mautrix_whatsapp file now contains twice the configuration, and logrotate complains about it.

$ sudo /usr/sbin/logrotate /etc/logrotate.conf
error: mautrix_signal:20 duplicate log entry for /var/log.hdd/mautrix_signal/mautrix_signal.log
error: found error in file mautrix_signal, skipping
error: mautrix_whatsapp:21 duplicate log entry for /var/log.hdd/mautrix_whatsapp/mautrix_whatsapp.log
error: found error in file mautrix_whatsapp, skipping

You should add this argument to the upgrade script.

If people (like me) already have this bug, the next upgrade will cleanup the issue because --nonappend overwrites the file.

**Comment by MayeulC** [comment]
Good catch, sounds fair

**Comment by Gredin67** [comment]
Was this solved already?

**Comment by MayeulC** [comment]
Sorry, I didn't have much time back when this happened, and this went over my head. PR in #51, cherry-picked in #52 for the compat branch though I am not sure if that will be very useful. Will merge both once CI is done in #51.

**Comment by Salamandar** [comment]
Nice !
