### ISSUE TITLE
Install : the column « signalbot » doesn't exist

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/mautrix_signal_ynh#6]
### Describe the bug

Attempt to install in Virtualbox for test. Install succeeded but when trying to invite signalbot, it's not answering and in the log of install I find that it hasn't been created...

### Context

- Hardware: Virtualbox
- YunoHost version: 4.6.2.1
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: Virtualbox without port open
### Steps to reproduce

Install with the command  `sudo yunohost app install https://github.com/YunoHost-Apps/mautrix_signal_ynh --debug
Success
Invite signalbot user, no answer

`### Expected behavior

signalbot should have been created and should answer to invitation

### Logs

https://paste.yunohost.org/raw/ofobejilij

The interesting part is

> 2021-07-27 15:10:15,409: DEBUG - + ynh_psql_connect_as --user=postgres --password=********** --database=matrix_synapse
> 2021-07-27 15:10:15,487: DEBUG - + database=matrix_synapse
> 2021-07-27 15:10:15,487: DEBUG - + sudo --login --user=postgres PGUSER=postgres PGPASSWORD=********** psql matrix_synapse
> 2021-07-27 15:10:15,571: WARNING - ERREUR:  la colonne « signalbot » n'existe pas
> 2021-07-27 15:10:15,573: WARNING - LIGNE 1 : UPDATE users SET admin = 1 WHERE name = signalbot;
> 2021-07-27 15:10:15,573: WARNING -                                                   ^
> 2021-07-27 15:10:15,583: DEBUG - + ynh_systemd_action --service_name=mautrix_signal --action=restart

I can't make it working on fresh install in Virtualbox. Sorry I couldn't help....

**Comment by rosbeef** [comment]
this worning is not blocking the installation in my case. mabe refer to the [#8
