### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/mautrix_signal_ynh#8]
Full logs here https://paste.yunohost.org/raw/bovapehuga

yunohost_version: 4.2.6.1

This seems to be the main error ` 2021-08-03 03:52:02,524: WARNING - Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-yfhfqiev/  `

**Comment by rosbeef** [comment]
same error here: https://paste.yunohost.org/raw/renahohiro
try pip3 install --upgrade setuptools
then it seems like people with that kind of bug install other tool.
But i don't know wich in our case.
I will try search

**Comment by rosbeef** [comment]
Trying to install with **yunohost app install mautrix_signal --debug** i have the next output :

> Complete output from command /opt/yunohost/mautrix_signal/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-whd3_g4p/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-_uy12p0d --python-tag cp37:
> 219182 DEBUG   usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
> 219183 DEBUG      or: -c --help [cmd1 cmd2 ...]
> 219183 DEBUG      or: -c --help-commands
> 219183 DEBUG      or: -c cmd --help
> 219184 DEBUG 
> 219184 DEBUG   error: invalid command 'bdist_wheel'
> 219184 DEBUG 
> 219185 DEBUG   ----------------------------------------
> 219185 DEBUG   Running setup.py clean for mautrix-signal
> 219185 WARNING   Failed building wheel for mautrix-signal
> 219707 DEBUG   Running setup.py bdist_wheel for aiohttp: started
>
